name: PR Checks

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: pip install -e '.[test]' && python -m pip install pytest
      - run: pytest
